# Generated by Django 3.2.12 on 2023-01-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='conetent',
            new_name='content',
        ),
    ]
